publish_to: none
name: snippet_generator
description: Visual Studio Code snippets/documentation generator.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  stream_transform: ^2.0.0
  pure: ^0.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  md:
    git:
      url: git@github.com:purplenoodlesoop/parsing-and-rendering.git
      path: packages/md
  fast_immutable_collections: ^7.4.2


dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  purple_lints: ^0.2.0
