name: snippet_generator
description: Visual Studio Code snippets/documentation generator.
version: 0.1.0

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  stream_transform: ^2.0.0
  pure: ^0.2.0


dev_dependencies:
  purple_lints: ^0.2.0
